$(nixos-rebuild list-generations | grep True)

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -14,14 +14,14 @@ git diff -U0 '*.nix'
 
 echo "Rebuilding..."
 
-alejandra . &>/dev/null \
-  || ( alejandra . ; echo "formatting failed!" && exit 1)
+alejandra . &>/dev/null || ( alejandra . ; echo "formatting failed!" && exit 1)
 
 sudo nixos-rebuild switch --flake .#nixos | tee nixos-switch.log
 
-current=$(nixos-rebuild list-generations | grep True)
-printf "Curent generation: %s\n" "$current"
-git commit -am "$current"
+# current=$(nixos-rebuild list-generations | grep True)
+# printf "Curent generation: %s\n" "$current"
+# git commit -am "$current"
+#
 popd
 
 echo "Rebuild Successful, changes applied"
